/* tslint:disable */
export const itemData = [
    {id: 1, name: 'Master Sword', class: 'One-Handed', traits: ['Master Sword Beam'], type: 'Sword', Compendium: '198/203', Attack:[30,40,50,60], Durability: 40, Description: 'The Legendary sword that seals the darkness. Its blade gleams with a sacred luster that can oppose the Calamity. Only a hero chosen by the sword itself may wield it.'},
    {id: 2, name: 'Tree Branch', class: 'One-Handed', traits: ['None'], type: 'Sword', Compendium: '199/204', Attack: 2, Durability: 4, Description: 'Wooden branches such as this are pretty common, but it\'s suprisingly well-balanced. It doesn\'t do much damage but can serve as a weapon in a pinch.'},
    {id: 3, name: 'Torch', class: 'One-Handed', traits: ['Can keep a fire without breaking'], type: 'Sword', Compendium: '200/205', Attack: 2, Durability: 8, Description: 'This torch will stay lit once ignited. If you put it away, the flame will be extinguished until you light it again.'},
    {id: 4, name: 'Soup Ladle', class: 'One-Handed', traits: ['None'], type: 'Sword', Compendium: '201/206', Attack: 4, Durability: 5, Description: 'A kitchen implement often used for serving delicious soups. It was carved from the wood of a sturdy tree, so it actually packs quite the wallop.'},
    {id: 5, name: 'Boomerang', class: 'One-Handed', traits: ['Returns after being thrown'], type: 'Sword', Compendium: '202/207', Attack: 8, Durability: 18, Description: 'This throwing weapon was originally used by the forest-dwelling Koroks. Its unique shape allows it to return after being thrown.'},
    {id: 6, name: 'Spring Loaded Hammer', class: 'One-Handed', traits: ['Launches enemys on the 4th swing'], type: 'Sword', Compendium: '203/208', Attack: 1, Durability: 80, Description: 'This strange hammer is one of Kilton\'s specialties. Being struck by it doesn\'t hurt much, but the fourth swing in a string of attacks will send the victim flying.'},
    {id: 7, name: 'Traveler\'s Sword', class: 'One-Handed', traits: ['None'], type: 'Sword', Compendium: '204/209', Attack: 5, Durability: 20, Description: '	A very common sword often kept by travelers to fend off small beasts. It\'s fairly durable, but a bit unreliable against monsters.'},
    {id: 8, name: 'Soldier\'s Broadsword', class: 'One-Handed', traits: ['None'], type: 'Sword', Compendium: '205/210', Attack: 14, Durability: 25, Description: 'A sword brandished by the soldiers who once protected Hyrule Castle. Its durable blade is well tuned for slaying monsters.'},
    {id: 9, name: 'Knight\'s Broadsword', class: 'One-Handed', traits: ['None'], type: 'Sword', Compendium: '206/211', Attack: 26, Durability: 27, Description: 'Knights of Hyrule once carried this sword. These days it\'s the weapon of choice for seasoned adventurers thanks to its ease of use and high attack power.'},
];
